version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: voip_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
      MONGO_INITDB_DATABASE: voipsuite
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
